export const defaultSong = {
  bpm: 146,
  blocks: 4,
  tracks: {
    crash: {
      type: "crash",
      name: "Crash",
      volume: 1,
      muted: false,
      steps: {},
    },
    ride: {
      type: "ride",
      name: "Ride",
      volume: 1,
      muted: false,
      steps: {},
    },
    "open-hi-hat": {
      type: "open-hi-hat",
      name: "Open Hi Hat",
      volume: 1,
      muted: false,
      steps: {},
    },
    "closed-hi-hat": {
      type: "closed-hi-hat",
      name: "Closed Hi Hat",
      volume: 1,
      muted: false,
      steps: {},
    },
    "high-tom": {
      type: "high-tom",
      name: "High tom",
      volume: 1,
      muted: false,
      steps: {},
    },
    "low-tom": {
      type: "low-tom",
      name: "Low tom",
      volume: 1,
      muted: false,
      steps: {},
    },
    "medium-tom": {
      type: "medium-tom",
      name: "Medium tom",
      volume: 1,
      muted: false,
      steps: {},
    },
    snare: {
      type: "snare",
      name: "Snare",
      volume: 1,
      muted: false,
      steps: { 5: true, 13: true },
    },
    kick: {
      type: "kick",
      name: "Kick",
      volume: 1,
      muted: false,
      steps: { 1: true, 4: true, 7: true, 11: true },
    },
  },
};
