"""kit_id on song

Revision ID: 678ff8b5c875
Revises: d97dcaff7055
Create Date: 2024-01-08 21:31:58.655356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '678ff8b5c875'
down_revision: Union[str, None] = 'd97dcaff7055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('kit_id', sa.String(length=36), nullable=True))
    op.drop_column('song', 'kit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('kit', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('song', 'kit_id')
    # ### end Alembic commands ###
